// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qukHFL-ce6evYTbcA5WuzsZmXwQstaQ',
    appId: '1:30389014806:web:19cd106e19602b6a010037',
    messagingSenderId: '30389014806',
    projectId: 'wastem-c5980',
    authDomain: 'wastem-c5980.firebaseapp.com',
    storageBucket: 'wastem-c5980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA27B1mMRcCPWQzj0c7vql-PGcBcglgfho',
    appId: '1:30389014806:android:2bbb47107c547d8e010037',
    messagingSenderId: '30389014806',
    projectId: 'wastem-c5980',
    storageBucket: 'wastem-c5980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeIx1q0-FxUpardhM3sY1BBuX7lBiI2L4',
    appId: '1:30389014806:ios:414a169550623db7010037',
    messagingSenderId: '30389014806',
    projectId: 'wastem-c5980',
    storageBucket: 'wastem-c5980.firebasestorage.app',
    iosBundleId: 'com.example.wastem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeIx1q0-FxUpardhM3sY1BBuX7lBiI2L4',
    appId: '1:30389014806:ios:414a169550623db7010037',
    messagingSenderId: '30389014806',
    projectId: 'wastem-c5980',
    storageBucket: 'wastem-c5980.firebasestorage.app',
    iosBundleId: 'com.example.wastem',
  );
}
